language: cpp
sudo: required
os:
  - linux
  - osx
  
compiler:
  - clang
  - gcc
  
before_install:
- if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update; fi
- if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install llvm38 && brew install openssl && brew link --force --overwrite llvm38; fi

branches:
  only:
  - master
  
notifications:
  email: false
