language: cpp

# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.7']
      env:
        - COMPILER=g++-4.7
        
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5.4']
      env:
        - COMPILER=g++-5.4

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5']
          packages: ['clang-3.5']
      env:
        - COMPILER=clang++-3.5
        
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5']
          packages: ['clang-3.8']
      env:
        - COMPILER=clang++-3.8
        
    - os: osx
      compiler: gcc
      env:
        - COMPILER=g++-4.7
        
    - os: osx
      compiler: clang
      env:
        - COMPILER=clang++-3.5
      
before_script:
  - export CXX=$COMPILER
  - cd MyTinySTL/Test
  
script:
  - make
  
branches:
  only:
  - master
  
notifications:
  email: false
