language: cpp

# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.6']
      env:
        - COMPILER=g++-4.6

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8']
      env:
        - COMPILER=g++-4.8

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env:
        - COMPILER=g++-5

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.3']
          packages: ['clang-3.3']
      env:
        - COMPILER=clang++-3.3

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.4']
          packages: ['clang-3.4']
      env:
        - COMPILER=clang++-3.4

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5']
          packages: ['clang-3.5']
      env:
        - COMPILER=clang++-3.5

    - os: osx
      compiler: gcc
      env:
        - COMPILER=g++-4.6
        
    - os: osx
      compiler: clang
      env:
        - COMPILER=clang++-3.3
      
before_script:
  - export CXX=$COMPILER

script:
  - cd MyTinySTL/Test
  - make
  
branches:
  only:
  - master
  
notifications:
  email: false
