language: cpp

sudo: required
dist: precise

compiler:
 - gcc
 - clang
 
branches:
  only:
  - master

before_install:
    - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
- sudo apt-get install -y cmake valgrind g++-multilib libc6-dbg:i386

notifications:
  email: false


