language: cpp
sudo: required
os:
  - linux
  - osx
  
compiler:
  - clang
  - gcc
  
before_install:
- if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update; fi
- if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install llvm38 && brew install openssl && brew link --force --overwrite llvm38; fi

before_script:
- if [ $TRAVIS_OS_NAME == linux ]; then travis_retry ./configure --llvm-config=llvm-config-3.8 --cc=clang-3.8 --cxx=clang++-3.8; fi
- if [ $TRAVIS_OS_NAME == osx ]; then travis_retry ./configure --with-include-dir=$OPENSSL_DIR/include --with-lib-dir=$OPENSSL_DIR/lib --llvm-config=llvm-config-3.8 --cc=clang-3.8 --cxx=clang++-3.8; fi

branches:
  only:
  - master
  
notifications:
  email: false
