version: 1.0.{build}

branches:
  only:
    - master
    
skip_commits:
  message: /Created.*\.(png|jpg|jpeg|bmp|gif)/
  
image: Visual Studio 2015

platform: Any CPU

configuration: Release

build:
  parallel: true
  project: MyTinySTL/MSVC/MyTinySTL.sln
